### ISSUE TITLE
Duplicated Timeseries issue after 5.8.2 upgrade

### ISSUE THREAD

**Issue by osheroff** [trallnag/prometheus-fastapi-instrumentator#152]
Hey, 
So my fastapi project automatically upgraded to the latest version of this project, and with 5.8.2 my server is failing to start with the following trace:

```
Traceback (most recent call last):
  File "/usr/local/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/main.py", line 437, in main
    run(app, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/main.py", line 463, in run
    server.run()
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1501, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/wg/vehicles/./api/main.py", line 50, in <module>
    async def setup_log_session(request: Request, call_next):
  File "/usr/local/lib/python3.8/dist-packages/starlette/applications.py", line 198, in decorator
    self.add_middleware(BaseHTTPMiddleware, dispatch=func)
  File "/usr/local/lib/python3.8/dist-packages/starlette/applications.py", line 127, in add_middleware
    self.middleware_stack = self.build_middleware_stack()
  File "/usr/local/lib/python3.8/dist-packages/starlette/applications.py", line 91, in build_middleware_stack
    app = cls(app=app, **options)
  File "/usr/local/lib/python3.8/dist-packages/prometheus_fastapi_instrumentator/middleware.py", line 52, in __init__
    self.instrumentations = instrumentations or [metrics.default()]
  File "/usr/local/lib/python3.8/dist-packages/prometheus_fastapi_instrumentator/metrics.py", line 544, in default
    TOTAL = Counter(
  File "/usr/local/lib/python3.8/dist-packages/prometheus_client/metrics.py", line 121, in __init__
    registry.register(self)
  File "/usr/local/lib/python3.8/dist-packages/prometheus_client/registry.py", line 29, in register
    raise ValueError(
ValueError: Duplicated timeseries in CollectorRegistry: {'http_requests_created', 'http_requests_total', 'http_requests'}
```

**Comment by eneiva** [comment]
Are you using async? if so, have you tried this? [link](https://github.com/trallnag/prometheus-fastapi-instrumentator/issues/80)

**Comment by Eytan-S** [comment]
Hi, I'm seeing the exact same issue, while using async like suggested in the link.
Getting this issue while using version 5.8.2. Rolling back to 5.7.1 fixes this.

**Comment by bralbral** [comment]
Same:

```

Traceback (most recent call last):
  File "/home/bral/PycharmProjects/elasticsearch_dbapi/main.py", line 13, in <module>
    uvicorn.run(
  File "/home/bral/PycharmProjects/elasticsearch_dbapi/venv/lib/python3.9/site-packages/uvicorn/main.py", line 575, in run
    server.run()
  File "/home/bral/PycharmProjects/elasticsearch_dbapi/venv/lib/python3.9/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1501, in uvloop.loop.Loop.run_until_complete
  File "/home/bral/PycharmProjects/elasticsearch_dbapi/venv/lib/python3.9/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/home/bral/PycharmProjects/elasticsearch_dbapi/venv/lib/python3.9/site-packages/uvicorn/config.py", line 479, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/bral/PycharmProjects/elasticsearch_dbapi/venv/lib/python3.9/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/bral/PycharmProjects/elasticsearch_dbapi/main.py", line 7, in <module>
    app = get_application()
  File "/home/bral/PycharmProjects/elasticsearch_dbapi/app/__init__.py", line 98, in get_application
    Instrumentator().instrument(_app).expose(_app)
  File "/home/bral/PycharmProjects/elasticsearch_dbapi/venv/lib/python3.9/site-packages/prometheus_fastapi_instrumentator/instrumentation.py", line 122, in instrument
    app.add_middleware(
  File "/home/bral/PycharmProjects/elasticsearch_dbapi/venv/lib/python3.9/site-packages/starlette/applications.py", line 169, in add_middleware
    self.middleware_stack = self.build_middleware_stack()
  File "/home/bral/PycharmProjects/elasticsearch_dbapi/venv/lib/python3.9/site-packages/fastapi/applications.py", line 194, in build_middleware_stack
    app = cls(app=app, **options)
  File "/home/bral/PycharmProjects/elasticsearch_dbapi/venv/lib/python3.9/site-packages/prometheus_fastapi_instrumentator/middleware.py", line 52, in __init__
    self.instrumentations = instrumentations or [metrics.default()]
  File "/home/bral/PycharmProjects/elasticsearch_dbapi/venv/lib/python3.9/site-packages/prometheus_fastapi_instrumentator/metrics.py", line 544, in default
    TOTAL = Counter(
  File "/home/bral/PycharmProjects/elasticsearch_dbapi/venv/lib/python3.9/site-packages/prometheus_client/metrics.py", line 143, in __init__
    registry.register(self)
  File "/home/bral/PycharmProjects/elasticsearch_dbapi/venv/lib/python3.9/site-packages/prometheus_client/registry.py", line 43, in register
    raise ValueError(
ValueError: Duplicated timeseries in CollectorRegistry: {'http_requests', 'http_requests_created', 'http_requests_total'}

Process finished with exit code 1
```

**Comment by zoola969** [comment]
> Are you using async? if so, have you tried this? [link](https://github.com/trallnag/prometheus-fastapi-instrumentator/issues/80)

Doesn't work for starlette>=0.24.0

**Comment by zoola969** [comment]
but works when the instrumentator is initialized outside from lifespan event handler.
```python
instrumentator = Instrumentator().instrument(app)

@app.on_event("startup")
async def startup_event() -> None:
     instrumentator.add(custom_metric()).expose(app)
```
